# Generated by Django 4.2.13 on 2024-07-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='raw_material',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
