# Generated by Django 4.2.13 on 2024-07-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0003_remove_orderitem_order_remove_orderitem_raw_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='vat',
        ),
    ]
