# Generated by Django 4.2.13 on 2024-07-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0004_remove_purchaseorderline_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='cost_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='vat_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
