# Generated by Django 4.2.13 on 2024-07-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0005_remove_purchaseorderline_purchase_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='cost_field',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='vat_field',
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='raw_materials.purchaseorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
