# Generated by Django 4.2.13 on 2024-07-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0006_remove_purchaseorderline_cost_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=24, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
