# Generated by Django 4.2.13 on 2024-07-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0007_purchaseorderline_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
