# Generated by Django 4.2.13 on 2024-07-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0008_alter_rawmaterial_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
