# Generated by Django 4.2.13 on 2024-08-06 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0014_purchaseorderline_invoiced_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_materials.rawmaterial'),
        ),
    ]
