# Generated by Django 4.2.13 on 2024-08-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0015_alter_purchaseinvoiceline_raw_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
