# Generated by Django 4.2.13 on 2024-08-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0016_purchaseinvoiceline_cost_purchaseinvoiceline_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='raw_materials.purchaseorderline'),
        ),
    ]
