# Generated by Django 4.2.13 on 2024-08-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0017_purchaseinvoiceline_order_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
